import json
import os
import sys
from typing import Any, Dict

CONFIG_FILE = "config.json"


def load_config() -> Dict[str, Any]:
    """Load runtime config from src/config.json (generated by run.sh in the add-on)."""
    base_dir = os.path.dirname(os.path.abspath(__file__))
    config_path = os.path.join(base_dir, CONFIG_FILE)

    if not os.path.exists(config_path):
        print(f"CRITICAL: Config file not found at {config_path}")
        sys.exit(1)

    with open(config_path, "r", encoding="utf-8") as f:
        config = json.load(f)

    if not isinstance(config, dict):
        print("CRITICAL: config.json must be a JSON object")
        sys.exit(1)

    # Ensure expected top-level sections exist
    config.setdefault("mqtt", {})
    config.setdefault("files", {})
    config.setdefault("device_info", {})
    config.setdefault("rf", {})

    # New TX power config defaults (human-friendly)
    rf = config["rf"]
    rf.setdefault("tx_power_mode", "smart")          # smart | max | default | manual
    rf.setdefault("tx_power_target_dbm", 0)          # -30..10 (table)
    rf.setdefault("tx_power_band", "auto")           # auto | 315 | 433 | 868 | 915

    # Advanced/manual escape hatches (only used when tx_power_mode == "manual")
    rf.setdefault("frend0_pa_power", None)               # 0..7
    rf.setdefault("frend0_lodiv_buf_current_tx", None)   # 0..3
    rf.setdefault("patable", None)                       # "0xC0" or "0x00,0x12,..."

    # Normalize the sub_directory path
    files = config["files"]
    raw_sub = files.get("sub_directory", "./tx_files")
    if isinstance(raw_sub, str) and raw_sub and not raw_sub.startswith("/"):
        files["sub_directory"] = os.path.join(base_dir, raw_sub)

    # Optional: allow running user-provided Python scripts from tx_files.
    # Disabled by default for safety.
    files.setdefault("allow_python_scripts", False)
    files.setdefault("python_timeout_s", 30)

    return config
